export const categories = [
  { name: "Electronics", icon: "\u{1F4BB}" },
  { name: "Fashion", icon: "\u{1F455}" },
  { name: "Home & Living", icon: "\u{1F6CB}\uFE0F" },
  { name: "Beauty", icon: "\u{1F484}" },
  { name: "Sports", icon: "\u{1F45F}" },
  { name: "Toys", icon: "\u{1F9F8}" },
  { name: "More", icon: "\u22EF" },
];
export const products = [
  {
    id: 1,
    name: "Wireless Headphones",
    category: "Electronics",
    price: 2999,
    oldPrice: 4999,
    rating: 4.5,
    reviews: 120,
    img: "\u{1F3A7}",
  },
  {
    id: 2,
    name: "Running Shoes",
    category: "Sports",
    price: 1899,
    oldPrice: 2999,
    rating: 4.5,
    reviews: 98,
    img: "\u{1F45F}",
  },
  {
    id: 3,
    name: "Smart Watch",
    category: "Electronics",
    price: 3499,
    oldPrice: 5999,
    rating: 4.5,
    reviews: 210,
    img: "\u231A",
  },
  {
    id: 4,
    name: "Travel Backpack",
    category: "Fashion",
    price: 1299,
    oldPrice: 2499,
    rating: 4.5,
    reviews: 86,
    img: "\u{1F392}",
  },
  {
    id: 5,
    name: "Bluetooth Speaker",
    category: "Electronics",
    price: 1599,
    oldPrice: 2499,
    rating: 4,
    reviews: 64,
    img: "\u{1F50A}",
  },
  {
    id: 6,
    name: "Cotton T-Shirt",
    category: "Fashion",
    price: 499,
    oldPrice: 999,
    rating: 4,
    reviews: 152,
    img: "\u{1F455}",
  },
  {
    id: 7,
    name: "Lipstick Set",
    category: "Beauty",
    price: 799,
    oldPrice: 1299,
    rating: 4.5,
    reviews: 77,
    img: "\u{1F484}",
  },
  {
    id: 8,
    name: "Teddy Bear",
    category: "Toys",
    price: 599,
    oldPrice: 999,
    rating: 5,
    reviews: 41,
    img: "\u{1F9F8}",
  },
  {
    id: 9,
    name: "Sofa Chair",
    category: "Home & Living",
    price: 8999,
    oldPrice: 12999,
    rating: 4,
    reviews: 33,
    img: "\u{1F6CB}\uFE0F",
  },
  {
    id: 10,
    name: "Laptop",
    category: "Electronics",
    price: 45999,
    oldPrice: 59999,
    rating: 4.5,
    reviews: 58,
    img: "\u{1F4BB}",
  },
];
